language: Objective-C
matrix:
 include:
  - osx_image: xcode8.2
env:
 global:
   - LC_CTYPE=en_US.UTF-8
git: 
 submodules: false
branches:
 only:
  - master
cache: 
 - bundler
 - cocoapods
script: 
 - xcodebuild test -workspace ESNotification.xcworkspace -scheme ESNotification_iOS -configuration Debug -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty -c 
notifications:   
 email: false
